### PR TITLE
Handle NULLs in SDKCall string return (Fixes #874)

### LINKED ISSUE #874: SDKCall crashes on null char pointers
# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): Team Fortress 2
  * SourceMod version (tested): 1.9.0.6238

# Description

SDKCalls that expect a char pointer but receive a null pointer instead seems to result in a segfault.  This was observed when calling TF2's `GetTFConditionName()` function on non-existent conditions.  The function itself has bounds checks and returns null on invalid conditions.

# Problematic Code

[Available as a gist here.](https://gist.github.com/nosoop/781c73a9e6583f05ce2bd3a465ad017b)  Prints out addresses by default (breaking out of the loop after cond 127 as expected); uncomment and comment accordingly to get the string returned instead (crashing instead of exiting the loop).

### PR DESCRIPTION
**Pull request by asherkin**
`SDKCall` has existing semantics that a `-1` retval indicates null, so use that and write an empty string to the buffer.

Consumers can tell the difference between `""` and `NULL` by checking if the return value is `0` or `-1`.

### CODE REVIEW

File: extensions/sdktools/vcaller.cpp [hunk 1]
```diff
@@ -449,6 +449,11 @@ static cell_t SDKCall(IPluginContext *pContext, const cell_t *params)
 			cell_t *addr;
 			size_t written;
 			pContext->LocalToPhysAddr(params[retparam+1], &addr);
+			if (!(*(char **)vc->retbuf))
```
Comment (Headline) [inline extensions/sdktools/vcaller.cpp]: `static_cast<>` ?

Comment (asherkin) [reply extensions/sdktools/vcaller.cpp]: I'm quite in-favour of consistently using C-style casts rather than mixing them, especially in a behemoth like this function.

Comment (Headline) [reply extensions/sdktools/vcaller.cpp]: i don’t think consistency is always a valid reason to avoid an approach that may be better, but we can stick to c-style casts as long as it’s already plagued in there everywhere.
