### PR TITLE
A2S_Rules fix: Move MTU patch value to gamedata

### LINKED ISSUE #1814: CS:GO A2S_Rules fix does not patch MTU high enough to accommodate all use cases
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Game/AppID (with version if applicable): CS:GO/730

# Description
https://github.com/alliedmodders/sourcemod/pull/614 brought the functionality of the [A2S_Rules hax plugin](https://forums.alliedmods.net/showthread.php?t=236521) directly into SM to fix CS:GO A2S_Rules responses. However while that plugin increased the MTU to 65k bytes, SM's implementation went with a [value of 5k instead](https://github.com/alliedmodders/sourcemod/blob/2f0ba0f34516157c7d5a873dbd16c9e5c4ed2a5d/extensions/cstrike/rulesfix.cpp#L83). This has proven to not be enough for some people that have plugins adding many `FCVAR_NOTIFY` flagged convars, and causes the A2S_Rules response to fail again after going past 5k bytes.

This should be be a fairly simple PR, but I was unsure of the reasoning for going with a lower value in the first place, and want to make sure there aren't any concerns with 65k or whatever other value may be preferred.

# Problematic Code (or Steps to Reproduce)
Enough convars created like this will eventually trigger the issue
```
ConVar cvar;

public void OnPluginStart()
{
	cvar = CreateConVar("sm_cvar_with_notify_flag", "0", "", FCVAR_NOTIFY);
}
```

# Logs
Some real world examples posted by several users in the SM Discord
```
[NET] Cannot send 6031-byte packet to ***:7130.  MTU is 1200.  ff ff ff ff 45
[NET] Cannot send 5171-byte packet to 195.201.249.154:47566.  MTU is 1200.  ff ff ff ff 45
[NET] Cannot send 5602-byte packet to [IP]. MTU is 1200. ff ff ff ff 45 
```

### PR DESCRIPTION
**Pull request by Vauff**
Fixes #1814, supersedes #1815.

Implements the suggestion from https://github.com/alliedmodders/sourcemod/pull/1459#pullrequestreview-638382759, and increases the MTU to 65000 (what was used in the old plugin).

### CODE REVIEW

**Review by WhiteAngel4 — APPROVED** [review]

**Comment by psychonic** [comment]
The MTU is already being patched to more than twice a sane MTU value. Making it configurable is fine, but we don't want it getting too huge and people potentially opening themselves up to DOSing if they actually do have that many convars with the notify flag or large values due to what would surely be hugely fragmented oob packets.

**Comment by Vauff** [comment]
> The MTU is already being patched to more than twice a sane MTU value. Making it configurable is fine, but we don't want it getting too huge and people potentially opening themselves up to DOSing if they actually do have that many convars with the notify flag or large values due to what would surely be hugely fragmented oob packets.

What value would be recommended here then? Or no increase at all?

File: extensions/cstrike/rulesfix.cpp [hunk 1]
```diff
@@ -53,7 +54,7 @@ bool SetMTUMax(int iValue)
 
 	//If we never changed skip resetting
 	if (iOriginalValue == -1 && iValue == -1)
-		return true;
+		return false;
```
Comment (asherkin) [inline extensions/cstrike/rulesfix.cpp:57]: What's this change for?

**Review by asherkin — COMMENTED** [review]
Definitely 👍 to making this configurable, not sure about changing the default value though.

> people potentially opening themselves up to DOSing if they actually do have that many convars with the notify flag or large values due to what would surely be hugely fragmented oob packets.

Is fragmented OOB reply packets much of a concern? I've never really understood Valve introducing a single-packet limit here as the OOB protocol is explicitly designed to be fragmented. Biggest concern I can see is SRCDS as a source of reflection attacks, but that's better solved through the challenge mechanism and ISP-level controls.

File: extensions/cstrike/rulesfix.cpp (hunk 1 above)
Comment (Vauff) [reply extensions/cstrike/rulesfix.cpp:57]: This is to prevent the lines 91-95 and 135-138 code blocks from running when the patch does not happen, since -1 can now be passed in those spots through iPatchSize's default value if the MTUPatchSize key is missing from gamedata.

**Comment by Vauff** [comment]
10k could possibly be a better middle ground? It would still cover all the reported "cannot send packet" instances so far without going too far overboard.

**Comment by KyleSanderson** [comment]
> 10k could possibly be a better middle ground? It would still cover all the reported "cannot send packet" instances so far without going too far overboard.

I do think 10k might be ok, but there's too many unknowns right now with us not understanding the full implications of what this does (such as the vulnerability potential mentioned). 10k is much larger than the internal we're already patching.

If you're open to it, if you change the gamedata value back to 5k we can land this, and then you can report back how 10k has worked for you (and others) after a period of time.

**Review by peace-maker — APPROVED** [review]

**Comment by crashzk** [comment]
@Vauff using the latest version **SourceMod 1.11.0.6934** I keep getting a lot of these errors.

```
[NET] Cannot send 5561-byte packet to XX.XXX.XX.XX:XXXXX.  MTU is 1200.  ff ff ff ff 45

[NET] Cannot send 5561-byte packet to XX.XXX.XX.XX:XXXXX.  MTU is 1200.  ff ff ff ff 45

[NET] Cannot send 5561-byte packet to XX.XXX.XX.XX:XXXXX.  MTU is 1200.  ff ff ff ff 45

[NET] Cannot send 5561-byte packet to XX.XXX.XX.XX:XXXXX.  MTU is 1200.  ff ff ff ff 45
```

**Comment by peace-maker** [comment]
Try increasing the `MTUPatchSize` in a custom gamedata override. It defaults to 5000 and you're having loads of convars with 5561 bytes.

**Comment by crashzk** [comment]
> Try increasing the `MTUPatchSize` in a custom gamedata override. It defaults to 5000 and you're having loads of convars with 5561 bytes.

Thanks for the reply. In any case, I noticed that SM 1.11 does not have this feature implemented yet, only in version 1.12+.

I even manually looked to change it in gamedata but it doesn't have this `MTUPatchSize`. For now, leave this spam on the console until I update to SM version 1.12.
