### PR TITLE
Cache created entities by reference instead of index in SDKHooks

### LINKED ISSUE #633: OnEntityCreated forward issue
_If you don't want to read how I came around the issue please jump to "What's the problem"_

Over the last months I've been making plugins relying on this forward to make fun stuff ect...
And sometimes the intended goal didn't work as expected and I thought it was just my code being bad, said plugin ran on 5 different servers and it happened on all of them.

Recently I've been making a plugin to remove the entity `tf_ammo_pack` on the game TF2, it worked well til I noticed an ammo pack hasn't been removed I remade and remade my code again and again with different approach it always ended up to the same problem, sometimes the ammo pack wasn't removed, so I came to the conclusion OnEntityCreated must be sometimes not called at all.

# What's the problem?
It seems the forward OnEntityCreated isn't called sometimes, this issue seems very very rare.

**General infos:**
- Linux server
- Running on game Team Fortress 2

**SourceMod Version Information:**
- SourceMod Version: 1.9.0.6059
- SourcePawn Engine: 1.9.0.6059, jit-x86 (build 1.9.0.6059)
- SourcePawn API: v1 = 4, v2 = 12
- Compiled on: Mar  5 2017 14:12:07
- Built from: https://github.com/alliedmodders/sourcemod/commit/9924a28
- Build ID: 6059:9924a28
- http://www.sourcemod.net/

**Metamod:Source version 1.10.6**
- Built from: https://github.com/alliedmodders/metamod-source/commit/9fed12f
- Build ID: 946:9fed12f
- Loaded As: Valve Server Plugin
- Compiled on: Sep 12 2015
- Plugin interface version: 15:14
- SourceHook version: 5:5
- http://www.metamodsource.net/

## How reproduce the bug?
In order to reproduce the bug easily I recommend spawning a group of 32 red bots on the map `itemtest` set `nb_blind` on 1, noclip to test room, slay all the bots so they respawn in that test room, and then load the plugin I've provided with that issue, and start melee crit kill every single bot til you see one ammo box on the ground.

Screenshot of the bug occurring, I killed several bots all ammo packs got kill except one: https://steamuserimages-a.akamaihd.net/ugc/848216256556038176/657D9768A29C20226867FCCA6C7F223A98B17BCD/

**Chat debug:**

```
Entity 1178 spawned (tf_ragdoll)
Entity 1175 spawned (tf_ammo_pack)
Entity 1181 spawned (tf_ragdoll)
Entity 1222 spawned (tf_ammo_pack)
Entity 1238 spawned (tf_ragdoll)
Entity 1202 spawned (tf_ammo_pack)
Entity 1207 spawned (tf_ragdoll)
//Missing debug chat line for a newly spawned tf_ammo_pack (the one we see in the screenshot)
```

### Plugin code
```
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

#pragma newdecls required

public Plugin myinfo = 
{
	name = "[TF2] OnEntityCreated bug", 
	author = "Benoist3012", 
	description = "", 
	version = "0.1", 
	url = ""
};

public void OnEntityCreated(int iEntity, const char[] classname)
{
	//Filtering out some spammy entity
	if (strncmp(classname, "tf_weapon", 9) != 0 && strcmp(classname, "instanced_scripted_scene") != 0 && strcmp(classname, "env_sniperdot") != 0 && strcmp(classname, "tf_dropped_weapon") != 0)
		PrintToChatAll("Entity %d spawned (%s)", iEntity, classname);
	if (strcmp(classname, "tf_ammo_pack") == 0)
	{
		SDKHook(iEntity, SDKHook_SetTransmit, Hook_PackSpawn);
		SDKHook(iEntity, SDKHook_Spawn, Hook_PackSpawn);
		AcceptEntityInput(iEntity, "Kill");
	}
}

public Action Hook_PackSpawn(int iEntity)
{
	return Plugin_Handled;
}
```

#### Theory

There's maybe some kind of check that gets activated randomly that blocks the call of created entity on the game, I don't know what exactly.
I have tried to kill all bots at once see if I could get (if the theory is right) the ammo packs of all bots.
And after countless try of all bots killed at once and no single ammo pack dropped I got this:
https://steamuserimages-a.akamaihd.net/ugc/848216256556177325/10FD4705AB09338823CAA97B5B63E80EA6BA6485/
The ammo pack of all bots spawned not even one missing, even though they should have all been deleted by the plugin, and as you can see in the chat all ammo pack debug line missing.
And on this screenshot we have the normal behavior
https://steamuserimages-a.akamaihd.net/ugc/848216256556197018/A4AE6DFA6E67D083368A33086D1EE5A25FB3186F/

Ps: I did upgrade my sourcemod to latest version, and I've also downgraded it, nothing worked for me. The same issue is happening with a similar plugin I stated in my intro on 5 different servers.

### PR DESCRIPTION
**Pull request by psychonic**
This fixes #633

### CODE REVIEW

File: extensions/sdkhooks/extension.h [hunk 1]
```diff
@@ -330,14 +329,18 @@ class SDKHooks :
...
+	void HandleEntityDeleted(CBaseEntity *pEntity);
 	void Unhook(CBaseEntity *pEntity);
 	void Unhook(IPluginContext *pContext);
 
 private:
 	int HandleOnTakeDamageHook(CTakeDamageInfoHack &info, SDKHookType hookType);
 	int HandleOnTakeDamageHookPost(CTakeDamageInfoHack &info, SDKHookType hookType);
+
+private:
+	inline bool IsEntityIndexInRange(int i) { return i >= 0 && i < NUM_ENT_ENTRIES; }
```
Comment (KyleSanderson) [inline extensions/sdkhooks/extension.h]: nit. sizeof.
