### PR TITLE
Update CGameConfig members to use std::string instead of fixed-size char arrays

### LINKED ISSUE #1381: Silent failure when accessing gamedata offset names >= 64 chars
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * ~~Current~~ Running SourceMod version: 1.10.0.6492
  * Current SourceMod snapshot: 1.11.0.6642
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.

# Description

A plugin I was prototyping has a gamedata offset named "ISchemaAttributeTypeBase::BSupportsGameplayModificationAndNetworking()", which is 70 chars long.

When attempting to read the value via `GameData.GetOffset`, it returns -1.  When using `PrepSDKCall_SetFromConf`, it returns `false`.

The name matches what is listed in the gameconf, so this ends up being an unexpected failure case.

Proposed solutions:

- Make the char array longer.
- Refactor to support strings of arbitrary length.
- Throw a proper exception at parse / retrieval time if handling a string that is too long (so the plugin author knows that the string needs to be shorter).

I don't want to go straight to PRing the first solution even if it's the easiest fix (as far as I know), would prefer to run it through the issue tracker first.

# Problematic Code (or Steps to Reproduce)

1. [See linked sample code and gameconfig.](https://gist.github.com/nosoop/060becd2936881faa6d77827233734ac)
2. Compile plugin and install plugin and gameconfig.  On plugin load, a message will be logged with the returned value of `GameConfGetOffset` on names with 64 and 63 characters.

### PR DESCRIPTION
**Pull request by nosoop**
Fixes #1381.

~~Currently marked as a draft since it's untested and there's still some fixed-size char arrays I need to look into under `AddressConf`.  Will test once those remaining things are looked at.~~ Tested in a TF2 server loaded up with a lot of gamedata.

### CODE REVIEW

File: core/logic/GameConfigs.cpp [hunk 1]
```diff
@@ -1074,11 +1074,11 @@ static inline unsigned minOf(unsigned a, unsigned b)
 	return a <= b ? a : b;
 }
 
-CGameConfig::AddressConf::AddressConf(char *sigName, unsigned sigLength, unsigned readCount, int *read, bool lastIsOffset)
+CGameConfig::AddressConf::AddressConf(std::string sigName, unsigned sigLength, unsigned readCount, int *read, bool lastIsOffset)
```
Comment (nosoop) [inline core/logic/GameConfigs.cpp:1077]: `sigLength` doesn't seem to be used. Might be safe to remove?

File: core/logic/GameConfigs.cpp [hunk 2]
```diff
@@ -241,7 +241,7 @@ SMCResult CGameConfig::ReadSMC_NewSection(const SMCStates *states, const char *n
 			{
 				m_ParseState = PSTATE_GAMEDEFS_KEYS;
 			}
-			else if ((strcmp(name, "#supported") == 0) && (strcmp(m_Game, "#default") == 0))
+			else if ((strcmp(name, "#supported") == 0) && (strcmp(m_Game.c_str(), "#default") == 0))
```
Comment (dvander) [inline core/logic/GameConfigs.cpp:244]: (m_Game == "#default")

if you prefer

File: core/logic/GameConfigs.cpp [hunk 3]
```diff
@@ -551,22 +551,22 @@ SMCResult CGameConfig::ReadSMC_LeavingSection(const SMCStates *states)
...
 					int val = gamehelpers->GetSendPropOffset(pProp);
-					m_Offsets.replace(m_offset, val);
-					m_Props.replace(m_offset, pProp);
+					m_Offsets.replace(m_offset.c_str(), val);
+					m_Props.replace(m_offset.c_str(), pProp);
 				} else {
 					/* Check if it's a non-default game and no offsets exist */
-					if (((strcmp(m_Game, "*") != 0) && strcmp(m_Game, "#default") != 0)
-						&& (!m_Offsets.retrieve(m_offset)))
+					if (((strcmp(m_Game.c_str(), "*") != 0) && strcmp(m_Game.c_str(), "#default") != 0)
```
Comment (dvander) [inline core/logic/GameConfigs.cpp:562]: m_Game != "*" && m_Game != "#default"

File: core/logic/GameConfigs.cpp [hunk 4]
```diff
@@ -692,8 +692,8 @@ SMCResult CGameConfig::ReadSMC_LeavingSection(const SMCStates *states)
 
 			if (m_Address[0] != '\0' && m_AddressSignature[0] != '\0')
 			{
-				AddressConf addrConf(m_AddressSignature, sizeof(m_AddressSignature), m_AddressReadCount, m_AddressRead, m_AddressLastIsOffset);
-				m_Addresses.replace(m_Address, addrConf);
+				AddressConf addrConf(m_AddressSignature, m_AddressSignature.length(), m_AddressReadCount, m_AddressRead, m_AddressLastIsOffset);
```
Comment (dvander) [inline core/logic/GameConfigs.cpp:695]: nit: prefer the canonical size() here

File: core/logic/GameConfigs.cpp (hunk 1 above)
Comment (dvander) [reply core/logic/GameConfigs.cpp:1077]: Yup, feel free to remove.

File: core/logic/GameConfigs.cpp [hunk 5]
```diff
@@ -1074,11 +1074,11 @@ static inline unsigned minOf(unsigned a, unsigned b)
 	return a <= b ? a : b;
 }
 
-CGameConfig::AddressConf::AddressConf(char *sigName, unsigned sigLength, unsigned readCount, int *read, bool lastIsOffset)
+CGameConfig::AddressConf::AddressConf(std::string sigName, unsigned sigLength, unsigned readCount, int *read, bool lastIsOffset)
 {
 	unsigned readLimit = minOf(readCount, sizeof(this->read) / sizeof(this->read[0]));
 
-	strncopy(signatureName, sigName, sizeof(signatureName) / sizeof(signatureName[0]));
+	this->signatureName = sigName;
```
Comment (dvander) [inline core/logic/GameConfigs.cpp:1081]: std::move(sigName)

**Review by dvander — CHANGES_REQUESTED** [review]
Thanks for doing this, it's great to see more C++-ification. This is fine to go in as-is, but there are a few tiny improvements to make.

File: core/logic/GameConfigs.cpp (hunk 5 above)
Comment (nosoop) [reply core/logic/GameConfigs.cpp]: Wasn't too sure early on if `m_AddressSignature` was going to be reused later, but yeah, moving it should be fine.

File: core/logic/GameConfigs.cpp [hunk 6]
```diff
@@ -551,22 +551,22 @@ SMCResult CGameConfig::ReadSMC_LeavingSection(const SMCStates *states)
 			if (m_Class[0] != '\0'
```
Comment (nosoop) [inline core/logic/GameConfigs.cpp:551]: Any opinion on whether to leave this as-is or switch these and other ones over to `.empty()`?

**Comment by nosoop** [comment]
Tested it as far as putting it on my test TF2 instance with all sorts of gamedata and verifying that it fixes #1381; will go ahead and toggle it off draft.

File: core/logic/GameConfigs.cpp [hunk 7]
```diff
@@ -1074,11 +1074,11 @@ static inline unsigned minOf(unsigned a, unsigned b)
 	return a <= b ? a : b;
 }
 
-CGameConfig::AddressConf::AddressConf(char *sigName, unsigned sigLength, unsigned readCount, int *read, bool lastIsOffset)
+CGameConfig::AddressConf::AddressConf(std::string sigName, unsigned readCount, int *read, bool lastIsOffset)
 {
 	unsigned readLimit = minOf(readCount, sizeof(this->read) / sizeof(this->read[0]));
 
-	strncopy(signatureName, sigName, sizeof(signatureName) / sizeof(signatureName[0]));
+	this->signatureName = std::move(sigName);
```
Comment (nosoop) [inline core/logic/GameConfigs.cpp:1081]: Wait a second; this still copies, doesn't it.  Should be a move assignment.

File: core/logic/GameConfigs.cpp (hunk 6 above)
Comment (dvander) [reply core/logic/GameConfigs.cpp:551]: empty() would be a nice bonus!

File: core/logic/GameConfigs.cpp [hunk 8]
```diff
@@ -1074,11 +1074,11 @@ static inline unsigned minOf(unsigned a, unsigned b)
 	return a <= b ? a : b;
 }
 
-CGameConfig::AddressConf::AddressConf(char *sigName, unsigned sigLength, unsigned readCount, int *read, bool lastIsOffset)
+CGameConfig::AddressConf::AddressConf(std::string&& sigName, unsigned readCount, int *read, bool lastIsOffset)
 {
 	unsigned readLimit = minOf(readCount, sizeof(this->read) / sizeof(this->read[0]));
 
-	strncopy(signatureName, sigName, sizeof(signatureName) / sizeof(signatureName[0]));
+	this->signatureName = sigName;
```
Comment (dvander) [inline core/logic/GameConfigs.cpp:1081]: You still need std::move() here to avoid a copy. "sigName" becomes an l-value, or something (I can't cite the rule book, but an explicit std::move is needed).

Comment (nosoop) [reply core/logic/GameConfigs.cpp]: Gotcha; not at all familiar with how moves work myself.

**Review by dvander — APPROVED** [review]

**Review by Headline — APPROVED** [review]
Looks great!

Thanks for taking the time to work on this
